---
driver:
  name: vagrant
  network:
  - ['forwarded_port', {guest: 3000, host: 3000, auto_correct: true}]

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5

suites:
  - name: package
    run_list:
      - recipe[uchiwa::default]
    attributes:
      uchiwa:
        api: [
          {
            name: sensu1,
            host: api1.example.com,
            port: 4567,
            ssl: false,
            timeout: 5000
          },
          {
            name: sensu2,
            host: api2.example.com,
            port: 4567,
            ssl: false,
            timeout: 5000
          }
        ]
        install_method: package

  - name: source
    run_list:
      - recipe[uchiwa::default]
    attributes:
      uchiwa:
        api: [
          {
            name: SJC Sensu,
            host: sensu-045.sjc1.sendgrid.net,
            port: 4567,
            ssl: false,
            timeout: 5000
          },
          {
            name: MDW sensu,
            host: sensu0001p1mdw1.sendgrid.net,
            port: 4567,
            ssl: false,
            timeout: 5000
          }
        ]
        install_method: source
        source_url: 'https://github.com/pauloconnor/uchiwa.git'
        version: 'stash_messages'

  - name: disabled_service
    excludes:
      - centos-7.0
      - ubuntu-12.04
      - ubuntu-14.04
    run_list:
      - recipe[uchiwa::default]
    attributes:
      uchiwa:
        api: [
          {
            name: SJC Sensu,
            host: sensu-045.sjc1.sendgrid.net,
            port: 4567,
            ssl: false,
            timeout: 5000
          },
          {
            name: MDW sensu,
            host: sensu0001p1mdw1.sendgrid.net,
            port: 4567,
            ssl: false,
            timeout: 5000
          }
        ]
        install_method: source
        manage_service: false
        version: ''
        source_url: 'https://github.com/pauloconnor/uchiwa.git'
